import React from 'react';
import Helmet from 'react-helmet';

const Layout = React.createClass({
  propTypes: {
    context: React.PropTypes.object.isRequired,
    markup: React.PropTypes.string.isRequired,
    state: React.PropTypes.string.isRequired
  },
  render: function() {
    const head = Helmet.rewind();

    // All the favicons and link and meta tags are generated by http://realfavicongenerator.net/
    return (
      <html>
        <head>
          <meta charSet="UTF-8"/>
          {head.title.toComponent()}
          {head.meta.toComponent()}
          <meta httpEquiv="X-UA-Compatible" content="IE=Edge,chrome=1"/>
          <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
          <link rel="stylesheet" href="/styles/main.css"/>

{/* Favicon markup below is generated by a gulp task */}
{/* Lack of indentation is undesired but inevitable */}
{/* fav */}
<link rel="apple-touch-icon" sizes="57x57" href="/images/apple-touch-icon-57x57.png" />
<link rel="apple-touch-icon" sizes="60x60" href="/images/apple-touch-icon-60x60.png" />
<link rel="apple-touch-icon" sizes="72x72" href="/images/apple-touch-icon-72x72.png" />
<link rel="apple-touch-icon" sizes="76x76" href="/images/apple-touch-icon-76x76.png" />
<link rel="apple-touch-icon" sizes="114x114" href="/images/apple-touch-icon-114x114.png" />
<link rel="apple-touch-icon" sizes="120x120" href="/images/apple-touch-icon-120x120.png" />
<link rel="apple-touch-icon" sizes="144x144" href="/images/apple-touch-icon-144x144.png" />
<link rel="apple-touch-icon" sizes="152x152" href="/images/apple-touch-icon-152x152.png" />
<link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-180x180.png" />
<link rel="icon" type="image/png" href="/images/favicon-32x32.png" sizes="32x32" />
<link rel="icon" type="image/png" href="/images/android-chrome-192x192.png" sizes="192x192" />
<link rel="icon" type="image/png" href="/images/favicon-96x96.png" sizes="96x96" />
<link rel="icon" type="image/png" href="/images/favicon-16x16.png" sizes="16x16" />
<link rel="manifest" href="/images/manifest.json" />
<link rel="mask-icon" href="/images/safari-pinned-tab.svg" color="#5bbad5" />
<link rel="shortcut icon" href="/images/favicon.ico" />
<meta name="msapplication-TileColor" content="#da532c" />
<meta name="msapplication-TileImage" content="/images/mstile-144x144.png" />
<meta name="msapplication-config" content="/images/browserconfig.xml" />
<meta name="theme-color" content="#ffffff" />
{/* /fav */}

        </head>
        <body>
          <div id="app" dangerouslySetInnerHTML={{ __html: this.props.markup }}></div>
          <script dangerouslySetInnerHTML={{ __html: this.props.state }}></script>
          <script src="/scripts/bundle.js"></script>
        </body>
      </html>
    );
  }
});

export default Layout;
